name: check

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: pn install
      - run: pn run build

  extract:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: pn install
      - run: pn run extract

  test:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: pn install
      - run: pn run test --coverage

  type-check:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: pn install
      - run: pn run type-check

  lint:
    uses: ./.github/workflows/lint.yml
